### ISSUE TITLE
Compilation issue with buried libiberty.h

### ISSUE THREAD

**Issue by tangentsoft** [nihilus/bflt-utils#1]
You might want to fix this issue upstream, so your users don't have to discover [the fix](http://unix.stackexchange.com/q/224681/138) themselves.

**Comment by nihilus** [comment]
Ah thx... I have not had the time to compile all repos yet. I will fix this during the weekend.

**Comment by nihilus** [comment]
@tangentsoft Actually this compiles fine on my Ubuntu installation. However I should add configure-scripts for finding the paths at best.
